#!/home/infres/dfouchard-21/miniconda3/envs/mase/bin/python
from chop.cli import ChopCLI

if __name__ == "__main__":
    # this if statement is necessary to spawn new processes for ddp
    ChopCLI().run()
